-- 01_enums.sql: PostgreSQL Custom Enumeration Types
CREATE TYPE "RepairStatus" AS ENUM ('RECEIVED', 'IN_PROGRESS', 'WAITING_PART', 'READY', 'DELIVERED', 'CANCELED');
CREATE TYPE "BuybackStatus" AS ENUM ('DRAFT', 'APPROVED', 'REJECTED', 'COMPLETED');
CREATE TYPE "ReconciliationStatus" AS ENUM ('NONE', 'SENT', 'VIEWED', 'APPROVED', 'REJECTED', 'EXPIRED');
CREATE TYPE "MailLogStatus" AS ENUM ('QUEUED', 'SENT', 'FAILED');
CREATE TYPE "SaleStatus" AS ENUM ('DRAFT', 'PAID', 'CANCELED', 'REFUNDED');
CREATE TYPE "LedgerType" AS ENUM ('DEBIT', 'CREDIT');
CREATE TYPE "TransactionType" AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE "PaymentMethod" AS ENUM ('CASH', 'CREDIT_CARD', 'ON_ACCOUNT');
CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'CASHIER', 'TECHNICIAN', 'MANAGER', 'ACCOUNTANT');
