-- 19_product_stockitem_variant_fields.sql
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "variantColor" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "variantStorage" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "serialNumber" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "imei" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "purchaseDocType" TEXT;
ALTER TABLE "StockItem" ADD COLUMN IF NOT EXISTS "purchaseDocNo" TEXT;

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "variantColor" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "variantStorage" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "serialNumber" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "imei" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "purchaseDocType" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "purchaseDocNo" TEXT;
